export const countries = [
  { id: 'AF', state: 'อัฟกานิสถาน', name: 'Afghanistan' },
  { id: 'AL', state: 'แอลเบเนีย', name: 'Albania' },
  { id: 'DZ', state: 'แอลจีเรีย', name: 'Algeria' },
  { id: 'AS', state: 'อเมริกันซามัว', name: 'American Samoa' },
  { id: 'AD', state: 'อันดอร์รา', name: 'Andorra' },
  { id: 'AO', state: 'แองโกลา', name: 'Angola' },
  { id: 'AI', state: 'แองกวิลลา', name: 'Anguilla' },
  { id: 'AQ', state: 'แอนตาร์กติกา', name: 'Antarctica' },
  { id: 'AG', state: 'แอนติกาและบาร์บูดา', name: 'Antigua and Barbuda' },
  { id: 'AR', state: 'อาร์เจนตินา', name: 'Argentina' },
  { id: 'AM', state: 'อาร์เมเนีย', name: 'Armenia' },
  { id: 'AW', state: 'อารูบา', name: 'Aruba' },
  { id: 'AU', state: 'ออสเตรเลีย', name: 'Australia' },
  { id: 'AT', state: 'ออสเตรีย', name: 'Austria' },
  { id: 'AZ', state: 'อาเซอร์ไบจาน', name: 'Azerbaijan' },
  { id: 'BS', state: 'บาฮามาส', name: 'Bahamas' },
  { id: 'BH', state: 'บาห์เรน', name: 'Bahrain' },
  { id: 'BD', state: 'บังกลาเทศ', name: 'Bangladesh' },
  { id: 'BB', state: 'บาร์เบโดส', name: 'Barbados' },
  { id: 'BY', state: 'เบลารุส', name: 'Belarus' },
  { id: 'BE', state: 'เบลเยียม', name: 'Belgium' },
  { id: 'BZ', state: 'เบลีซ', name: 'Belize' },
  { id: 'BJ', state: 'เบนิน', name: 'Benin' },
  { id: 'BM', state: 'เบอร์มิวดา', name: 'Bermuda' },
  { id: 'BT', state: 'ภูฏาน', name: 'Bhutan' },
  { id: 'BO', state: 'โบลิเวีย', name: 'Bolivia' },
  {
    id: 'BQ',
    state: 'โบแนร์ ซินต์เอิสตาซียึส และซาบา',
    name: 'Bonaire, Sint Eustatius, and Saba',
  },
  {
    id: 'BA',
    state: 'บอสเนียและเฮอร์เซโกวีนา',
    name: 'Bosnia and Herzegovina',
  },
  { id: 'BW', state: 'บอตสวานา', name: 'Botswana' },
  { id: 'BV', state: 'เกาะบูเว', name: 'Bouvet Island' },
  { id: 'BR', state: 'บราซิล', name: 'Brazil' },
  {
    id: 'IO',
    state: 'บริติชอินเดียนโอเชียนเทร์ริทอรี',
    name: 'British Indian Ocean Territory',
  },
  { id: 'BN', state: 'บรูไน', name: 'Brunei' },
  { id: 'BG', state: 'บัลแกเรีย', name: 'Bulgaria' },
  { id: 'BF', state: 'บูร์กินาฟาโซ', name: 'Burkina Faso' },
  { id: 'BI', state: 'บุรุนดี', name: 'Burundi' },
  { id: 'CV', state: 'เคปเวิร์ด', name: 'Cabo Verde' },
  { id: 'KH', state: 'กัมพูชา', name: 'Cambodia' },
  { id: 'CM', state: 'แคเมอรูน', name: 'Cameroon' },
  { id: 'CA', state: 'แคนาดา', name: 'Canada' },
  { id: 'KY', state: 'หมู่เกาะเคย์แมน', name: 'Cayman Islands' },
  { id: 'CF', state: 'สาธารณรัฐแอฟริกากลาง', name: 'Central African Republic' },
  { id: 'TD', state: 'ชาด', name: 'Chad' },
  { id: 'CL', state: 'ชิลี', name: 'Chile' },
  { id: 'CN', state: 'จีน', name: 'China' },
  { id: 'CX', state: 'เกาะคริสต์มาส', name: 'Christmas Island' },
  { id: 'CC', state: 'หมู่เกาะโคโคส', name: 'Cocos (Keeling) Islands' },
  { id: 'CO', state: 'โคลอมเบีย', name: 'Colombia' },
  { id: 'KM', state: 'คอโมโรส', name: 'Comoros' },
  { id: 'CG', state: 'สาธารณรัฐคองโก', name: 'Congo (Congo-Brazzaville)' },
  { id: 'CD', state: 'สาธารณรัฐประชาธิปไตยคองโก', name: 'Congo (DRC)' },
  { id: 'CK', state: 'หมู่เกาะคุก', name: 'Cook Islands' },
  { id: 'CR', state: 'คอสตาริกา', name: 'Costa Rica' },
  { id: 'HR', state: 'โครเอเชีย', name: 'Croatia' },
  { id: 'CU', state: 'คิวบา', name: 'Cuba' },
  { id: 'CW', state: 'คูราเซา', name: 'Curaçao' },
  { id: 'CY', state: 'ไซปรัส', name: 'Cyprus' },
  { id: 'CZ', state: 'สาธารณรัฐเช็ก', name: 'Czech Republic' },
  { id: 'DK', state: 'เดนมาร์ก', name: 'Denmark' },
  { id: 'DJ', state: 'จิบูตี', name: 'Djibouti' },
  { id: 'DM', state: 'โดมินิกา', name: 'Dominica' },
  { id: 'DO', state: 'สาธารณรัฐโดมินิกัน', name: 'Dominican Republic' },
  { id: 'EC', state: 'เอกวาดอร์', name: 'Ecuador' },
  { id: 'EG', state: 'อียิปต์', name: 'Egypt' },
  { id: 'SV', state: 'เอลซัลวาดอร์', name: 'El Salvador' },
  { id: 'GQ', state: 'อิเควทอเรียลกินี', name: 'Equatorial Guinea' },
  { id: 'ER', state: 'เอริเทรีย', name: 'Eritrea' },
  { id: 'EE', state: 'เอสโตเนีย', name: 'Estonia' },
  { id: 'ET', state: 'เอธิโอเปีย', name: 'Ethiopia' },
  {
    id: 'FK',
    state: 'หมู่เกาะฟอล์กแลนด์',
    name: 'Falkland Islands (Malvinas)',
  },
  { id: 'FO', state: 'หมู่เกาะแฟโร', name: 'Faroe Islands' },
  { id: 'FJ', state: 'ฟิจิ', name: 'Fiji' },
  { id: 'FI', state: 'ฟินแลนด์', name: 'Finland' },
  { id: 'FR', state: 'ฝรั่งเศส', name: 'France' },
  { id: 'GF', state: 'เฟรนช์เกียนา', name: 'French Guiana' },
  { id: 'PF', state: 'เฟรนช์พอลินีเชีย', name: 'French Polynesia' },
  {
    id: 'TF',
    state: 'เฟรนช์เซาเทิร์นเทร์ริทอรีส์',
    name: 'French Southern Territories',
  },
  { id: 'GA', state: 'กาบอง', name: 'Gabon' },
  { id: 'GM', state: 'แกมเบีย', name: 'Gambia' },
  { id: 'GE', state: 'จอร์เจีย', name: 'Georgia' },
  { id: 'DE', state: 'เยอรมนี', name: 'Germany' },
  { id: 'GH', state: 'กานา', name: 'Ghana' },
  { id: 'GI', state: 'ยิบรอลตาร์', name: 'Gibraltar' },
  { id: 'GR', state: 'กรีซ', name: 'Greece' },
  { id: 'GL', state: 'กรีนแลนด์', name: 'Greenland' },
  { id: 'GD', state: 'เกรเนดา', name: 'Grenada' },
  { id: 'GP', state: 'กวาเดอลูป', name: 'Guadeloupe' },
  { id: 'GU', state: 'กวม', name: 'Guam' },
  { id: 'GT', state: 'กัวเตมาลา', name: 'Guatemala' },
  { id: 'GG', state: 'เกิร์นซีย์', name: 'Guernsey' },
  { id: 'GN', state: 'กินี', name: 'Guinea' },
  { id: 'GW', state: 'กินี-บิสเซา', name: 'Guinea-Bissau' },
  { id: 'GY', state: 'กายอานา', name: 'Guyana' },
  { id: 'HT', state: 'เฮติ', name: 'Haiti' },
  {
    id: 'HM',
    state: 'เกาะเฮิร์ดและหมู่เกาะแมคโดนัลด์',
    name: 'Heard Island and McDonald Islands',
  },
  { id: 'VA', state: 'นครรัฐวาติกัน', name: 'Holy See (Vatican City State)' },
  { id: 'HN', state: 'ฮอนดูรัส', name: 'Honduras' },
  { id: 'HK', state: 'ฮ่องกง', name: 'Hong Kong' },
  { id: 'HU', state: 'ฮังการี', name: 'Hungary' },
  { id: 'IS', state: 'ไอซ์แลนด์', name: 'Iceland' },
  { id: 'IN', state: 'อินเดีย', name: 'India' },
  { id: 'ID', state: 'อินโดนีเซีย', name: 'Indonesia' },
  { id: 'IR', state: 'อิหร่าน', name: 'Iran' },
  { id: 'IQ', state: 'อิรัก', name: 'Iraq' },
  { id: 'IE', state: 'ไอร์แลนด์', name: 'Ireland' },
  { id: 'IM', state: 'เกาะแมน', name: 'Isle of Man' },
  { id: 'IL', state: 'อิสราเอล', name: 'Israel' },
  { id: 'IT', state: 'อิตาลี', name: 'Italy' },
  { id: 'JM', state: 'จาเมกา', name: 'Jamaica' },
  { id: 'JP', state: 'ญี่ปุ่น', name: 'Japan' },
  { id: 'JE', state: 'เจอร์ซีย์', name: 'Jersey' },
  { id: 'JO', state: 'จอร์แดน', name: 'Jordan' },
  { id: 'KZ', state: 'คาซัคสถาน', name: 'Kazakhstan' },
  { id: 'KE', state: 'เคนยา', name: 'Kenya' },
  { id: 'KI', state: 'คิริบาส', name: 'Kiribati' },
  { id: 'KP', state: 'เกาหลีเหนือ', name: 'Korea (North)' },
  { id: 'KR', state: 'เกาหลีใต้', name: 'Korea (South)' },
  { id: 'KW', state: 'คูเวต', name: 'Kuwait' },
  { id: 'KG', state: 'คีร์กีซสถาน', name: 'Kyrgyzstan' },
  { id: 'LA', state: 'ลาว', name: 'Laos' },
  { id: 'LV', state: 'ลัตเวีย', name: 'Latvia' },
  { id: 'LB', state: 'เลบานอน', name: 'Lebanon' },
  { id: 'LS', state: 'เลโซโท', name: 'Lesotho' },
  { id: 'LR', state: 'ไลบีเรีย', name: 'Liberia' },
  { id: 'LY', state: 'ลิเบีย', name: 'Libya' },
  { id: 'LI', state: 'ลิกเตนสไตน์', name: 'Liechtenstein' },
  { id: 'LT', state: 'ลิทัวเนีย', name: 'Lithuania' },
  { id: 'LU', state: 'ลักเซมเบิร์ก', name: 'Luxembourg' },
  { id: 'MO', state: 'มาเก๊า', name: 'Macao' },
  { id: 'MK', state: 'มาซิโดเนียเหนือ', name: 'Macedonia (FYROM)' },
  { id: 'MG', state: 'มาดากัสการ์', name: 'Madagascar' },
  { id: 'MW', state: 'มาลาวี', name: 'Malawi' },
  { id: 'MY', state: 'มาเลเซีย', name: 'Malaysia' },
  { id: 'MV', state: 'มัลดีฟส์', name: 'Maldives' },
  { id: 'ML', state: 'มาลี', name: 'Mali' },
  { id: 'MT', state: 'มอลตา', name: 'Malta' },
  { id: 'MH', state: 'หมู่เกาะมาร์แชลล์', name: 'Marshall Islands' },
  { id: 'MQ', state: 'มาร์ตินีก', name: 'Martinique' },
  { id: 'MR', state: 'มอริเตเนีย', name: 'Mauritania' },
  { id: 'MU', state: 'มอริเชียส', name: 'Mauritius' },
  { id: 'YT', state: 'มายอต', name: 'Mayotte' },
  { id: 'MX', state: 'เม็กซิโก', name: 'Mexico' },
  { id: 'FM', state: 'ไมโครนีเซีย', name: 'Micronesia' },
  { id: 'MD', state: 'มอลโดวา', name: 'Moldova' },
  { id: 'MC', state: 'โมนาโก', name: 'Monaco' },
  { id: 'MN', state: 'มองโกเลีย', name: 'Mongolia' },
  { id: 'ME', state: 'มอนเตเนโกร', name: 'Montenegro' },
  { id: 'MS', state: 'มอนต์เซอร์รัต', name: 'Montserrat' },
  { id: 'MA', state: 'โมร็อกโก', name: 'Morocco' },
  { id: 'MZ', state: 'โมซัมบิก', name: 'Mozambique' },
  { id: 'MM', state: 'เมียนมาร์', name: 'Myanmar (Burma)' },
  { id: 'NA', state: 'นามิเบีย', name: 'Namibia' },
  { id: 'NR', state: 'นาอูรู', name: 'Nauru' },
  { id: 'NP', state: 'เนปาล', name: 'Nepal' },
  { id: 'NL', state: 'เนเธอร์แลนด์', name: 'Netherlands' },
  { id: 'NC', state: 'นิวแคลิโดเนีย', name: 'New Caledonia' },
  { id: 'NZ', state: 'นิวซีแลนด์', name: 'New Zealand' },
  { id: 'NI', state: 'นิการากัว', name: 'Nicaragua' },
  { id: 'NE', state: 'ไนเจอร์', name: 'Niger' },
  { id: 'NG', state: 'ไนจีเรีย', name: 'Nigeria' },
  { id: 'NU', state: 'นีอูเอ', name: 'Niue' },
  { id: 'NF', state: 'เกาะนอร์ฟอล์ก', name: 'Norfolk Island' },
  {
    id: 'MP',
    state: 'หมู่เกาะนอร์เทิร์นมาเรียนา',
    name: 'Northern Mariana Islands',
  },
  { id: 'NO', state: 'นอร์เวย์', name: 'Norway' },
  { id: 'OM', state: 'โอมาน', name: 'Oman' },
  { id: 'PK', state: 'ปากีสถาน', name: 'Pakistan' },
  { id: 'PW', state: 'ปาเลา', name: 'Palau' },
  { id: 'PS', state: 'ปาเลสไตน์', name: 'Palestine' },
  { id: 'PA', state: 'ปานามา', name: 'Panama' },
  { id: 'PG', state: 'ปาปัวนิวกินี', name: 'Papua New Guinea' },
  { id: 'PY', state: 'ปารากวัย', name: 'Paraguay' },
  { id: 'PE', state: 'เปรู', name: 'Peru' },
  { id: 'PH', state: 'ฟิลิปปินส์', name: 'Philippines' },
  { id: 'PN', state: 'หมู่เกาะพิตแคร์น', name: 'Pitcairn Islands' },
  { id: 'PL', state: 'โปแลนด์', name: 'Poland' },
  { id: 'PT', state: 'โปรตุเกส', name: 'Portugal' },
  { id: 'PR', state: 'เปอร์โตริโก', name: 'Puerto Rico' },
  { id: 'QA', state: 'กาตาร์', name: 'Qatar' },
  { id: 'RO', state: 'โรมาเนีย', name: 'Romania' },
  { id: 'RU', state: 'รัสเซีย', name: 'Russia' },
  { id: 'RW', state: 'รวันดา', name: 'Rwanda' },
  { id: 'RE', state: 'เรอูนียง', name: 'Réunion' },
  { id: 'BL', state: 'เซนต์บาร์เธเลมี', name: 'Saint Barthélemy' },
  { id: 'SH', state: 'เซนต์เฮเลนา', name: 'Saint Helena' },
  { id: 'KN', state: 'เซนต์คิตส์ และเนวิส', name: 'Saint Kitts and Nevis' },
  { id: 'LC', state: 'เซนต์ลูเซีย', name: 'Saint Lucia' },
  { id: 'MF', state: 'เซนต์มาร์ติน', name: 'Saint Martin (French part)' },
  {
    id: 'PM',
    state: 'แซงปีแยร์และมิเกอลอง',
    name: 'Saint Pierre and Miquelon',
  },
  {
    id: 'VC',
    state: 'เซนต์วินเซนต์และเกรนาดีนส์',
    name: 'Saint Vincent and the Grenadines',
  },
  { id: 'WS', state: 'ซามัว', name: 'Samoa' },
  { id: 'SM', state: 'ซานมารีโน', name: 'San Marino' },
  { id: 'ST', state: 'เซาตูเมและปรินซิปี', name: 'São Tomé and Príncipe' },
  { id: 'SA', state: 'ซาอุดีอาระเบีย', name: 'Saudi Arabia' },
  { id: 'SN', state: 'เซเนกัล', name: 'Senegal' },
  { id: 'RS', state: 'เซอร์เบีย', name: 'Serbia' },
  { id: 'SC', state: 'เซเชลส์', name: 'Seychelles' },
  { id: 'SL', state: 'เซียร์ราลีโอน', name: 'Sierra Leone' },
  { id: 'SG', state: 'สิงคโปร์', name: 'Singapore' },
  { id: 'SX', state: 'ซินต์มาร์เทิน', name: 'Sint Maarten' },
  { id: 'SK', state: 'สโลวะเกีย', name: 'Slovakia' },
  { id: 'SI', state: 'สโลวีเนีย', name: 'Slovenia' },
  { id: 'SB', state: 'หมู่เกาะโซโลมอน', name: 'Solomon Islands' },
  { id: 'SO', state: 'โซมาเลีย', name: 'Somalia' },
  { id: 'ZA', state: 'แอฟริกาใต้', name: 'South Africa' },
  {
    id: 'GS',
    state: 'เจ้าหน้าที่รัฐใต้ของกระบี่และหมู่เกาะแซนด์วิช',
    name: 'South Georgia and the South Sandwich Islands',
  },
  { id: 'SS', state: 'ซูดานใต้', name: 'South Sudan' },
  { id: 'ES', state: 'สเปน', name: 'Spain' },
  { id: 'LK', state: 'ศรีลังกา', name: 'Sri Lanka' },
  { id: 'SD', state: 'ซูดาน', name: 'Sudan' },
  { id: 'SR', state: 'ซูรินาเม', name: 'Suriname' },
  { id: 'SJ', state: 'สฟาลบาร์และยานไมเอน', name: 'Svalbard and Jan Mayen' },
  { id: 'SZ', state: 'สวาซิแลนด์', name: 'Swaziland' },
  { id: 'SE', state: 'สวีเดน', name: 'Sweden' },
  { id: 'CH', state: 'สวิตเซอร์แลนด์', name: 'Switzerland' },
  { id: 'SY', state: 'ซีเรีย', name: 'Syria' },
  { id: 'TW', state: 'ไต้หวัน', name: 'Taiwan' },
  { id: 'TJ', state: 'ทาจิกิสถาน', name: 'Tajikistan' },
  { id: 'TZ', state: 'แทนซาเนีย', name: 'Tanzania' },
  { id: 'TH', state: 'ไทย', name: 'Thailand' },
  { id: 'TL', state: 'ติมอร์-เลสเต', name: 'Timor-Leste' },
  { id: 'TG', state: 'โตโก', name: 'Togo' },
  { id: 'TK', state: 'โตเกเลา', name: 'Tokelau' },
  { id: 'TO', state: 'ตองกา', name: 'Tonga' },
  { id: 'TT', state: 'ตรินิแดดและโตเบโก', name: 'Trinidad and Tobago' },
  { id: 'TN', state: 'ตูนิเซีย', name: 'Tunisia' },
  { id: 'TR', state: 'ตุรกี', name: 'Turkey' },
  { id: 'TM', state: 'เติร์กเมนิสถาน', name: 'Turkmenistan' },
  {
    id: 'TC',
    state: 'หมู่เกาะเติกส์และหมู่เกาะเคคอส',
    name: 'Turks and Caicos Islands',
  },
  { id: 'TV', state: 'ตูวาลู', name: 'Tuvalu' },
  { id: 'UG', state: 'ยูกันดา', name: 'Uganda' },
  { id: 'UA', state: 'ยูเครน', name: 'Ukraine' },
  { id: 'AE', state: 'สหรัฐอาหรับเอมิเรตส์', name: 'United Arab Emirates' },
  { id: 'GB', state: 'สหราชอาณาจักร', name: 'United Kingdom' },
  { id: 'US', state: 'สหรัฐอเมริกา', name: 'United States' },
  {
    id: 'UM',
    state: 'หมู่เกาะรอบนอกของสหรัฐอเมริกา',
    name: 'United States Minor Outlying Islands',
  },
  { id: 'UY', state: 'อุรุกวัย', name: 'Uruguay' },
  { id: 'UZ', state: 'อุซเบกิสถาน', name: 'Uzbekistan' },
  { id: 'VU', state: 'วานูอาตู', name: 'Vanuatu' },
  { id: 'VE', state: 'เวเนซุเอลา', name: 'Venezuela' },
  { id: 'VN', state: 'เวียดนาม', name: 'Vietnam' },
  {
    id: 'VG',
    state: 'หมู่เกาะบริติชเวอร์จิน',
    name: 'Virgin Islands, British',
  },
  {
    id: 'VI',
    state: 'หมู่เกาะเวอร์จินของสหรัฐอเมริกา',
    name: 'Virgin Islands, U.S.',
  },
  { id: 'WF', state: 'วาลลิสและฟุตูนา', name: 'Wallis and Futuna' },
  { id: 'EH', state: 'ซาฮาราตะวันตก', name: 'Western Sahara' },
  { id: 'YE', state: 'เยเมน', name: 'Yemen' },
  { id: 'ZM', state: 'แซมเบีย', name: 'Zambia' },
  { id: 'ZW', state: 'ซิมบับเว', name: 'Zimbabwe' },
];
